#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("IntentsSample.Resource", IsApplication=true)]

namespace IntentsSample
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int fragment_close_enter = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int fragment_close_exit = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int fragment_fade_enter = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int fragment_fade_exit = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int fragment_fast_out_extra_slow_in = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int fragment_open_enter = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int fragment_open_exit = 2130771974;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int alpha = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int font = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int fontProviderAuthority = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int fontProviderCerts = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int fontProviderFetchStrategy = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int fontProviderFetchTimeout = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int fontProviderPackage = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int fontProviderQuery = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int fontStyle = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int fontVariationSettings = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int fontWeight = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int ttcIndex = 2130837515;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int androidx_core_ripple_material_light = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int androidx_core_secondary_text_default_material_light = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int notification_action_color_filter = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int notification_icon_bg_color = 2130903043;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public const int compat_button_inset_horizontal_material = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int compat_button_inset_vertical_material = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int compat_button_padding_horizontal_material = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int compat_button_padding_vertical_material = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int compat_control_corner_material = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int compat_notification_large_icon_max_height = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int compat_notification_large_icon_max_width = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int notification_action_icon_size = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int notification_action_text_size = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int notification_big_circle_margin = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int notification_content_margin_start = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int notification_large_icon_height = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int notification_large_icon_width = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int notification_main_column_padding_top = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int notification_media_narrow_margin = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int notification_right_icon_size = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int notification_right_side_padding_top = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int notification_small_icon_background_padding = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int notification_small_icon_size_as_large = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int notification_subtext_size = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int notification_top_pad = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int notification_top_pad_large_text = 2130968597;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public const int notification_action_background = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int notification_bg = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int notification_bg_low = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int notification_bg_low_normal = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int notification_bg_low_pressed = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int notification_bg_normal = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int notification_bg_normal_pressed = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int notification_icon_background = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int notification_template_icon_bg = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int notification_template_icon_low_bg = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int notification_tile_bg = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int notify_panel_notification_icon_bg = 2131034123;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060000
			public const int accessibility_action_clickable_span = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int accessibility_custom_action_0 = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int accessibility_custom_action_1 = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int accessibility_custom_action_10 = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int accessibility_custom_action_11 = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int accessibility_custom_action_12 = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int accessibility_custom_action_13 = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int accessibility_custom_action_14 = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int accessibility_custom_action_15 = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int accessibility_custom_action_16 = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int accessibility_custom_action_17 = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int accessibility_custom_action_18 = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int accessibility_custom_action_19 = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int accessibility_custom_action_2 = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int accessibility_custom_action_20 = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int accessibility_custom_action_21 = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int accessibility_custom_action_22 = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int accessibility_custom_action_23 = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int accessibility_custom_action_24 = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int accessibility_custom_action_25 = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int accessibility_custom_action_26 = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int accessibility_custom_action_27 = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int accessibility_custom_action_28 = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int accessibility_custom_action_29 = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int accessibility_custom_action_3 = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int accessibility_custom_action_30 = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int accessibility_custom_action_31 = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int accessibility_custom_action_4 = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int accessibility_custom_action_5 = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int accessibility_custom_action_6 = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int accessibility_custom_action_7 = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int accessibility_custom_action_8 = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int accessibility_custom_action_9 = 2131099680;
			
			// aapt resource value: 0x7F060025
			public const int actions = 2131099685;
			
			// aapt resource value: 0x7F060021
			public const int action_container = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int action_divider = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int action_image = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int action_text = 2131099684;
			
			// aapt resource value: 0x7F060026
			public const int albuns = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int async = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int blocking = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int button_call = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int button_contacts = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int button_fragments = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public const int button_maps_coordinates = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int button_maps_routes = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public const int button_maps_street = 2131099694;
			
			// aapt resource value: 0x7F06002F
			public const int button_open_browser = 2131099695;
			
			// aapt resource value: 0x7F060030
			public const int chronometer = 2131099696;
			
			// aapt resource value: 0x7F060031
			public const int dialog_button = 2131099697;
			
			// aapt resource value: 0x7F060032
			public const int forever = 2131099698;
			
			// aapt resource value: 0x7F060033
			public const int fragment_container_view_tag = 2131099699;
			
			// aapt resource value: 0x7F060034
			public const int icon = 2131099700;
			
			// aapt resource value: 0x7F060035
			public const int icon_group = 2131099701;
			
			// aapt resource value: 0x7F060036
			public const int info = 2131099702;
			
			// aapt resource value: 0x7F060037
			public const int italic = 2131099703;
			
			// aapt resource value: 0x7F060038
			public const int line1 = 2131099704;
			
			// aapt resource value: 0x7F060039
			public const int line3 = 2131099705;
			
			// aapt resource value: 0x7F06003A
			public const int normal = 2131099706;
			
			// aapt resource value: 0x7F06003B
			public const int notification_background = 2131099707;
			
			// aapt resource value: 0x7F06003C
			public const int notification_main_column = 2131099708;
			
			// aapt resource value: 0x7F06003D
			public const int notification_main_column_container = 2131099709;
			
			// aapt resource value: 0x7F06003E
			public const int right_icon = 2131099710;
			
			// aapt resource value: 0x7F06003F
			public const int right_side = 2131099711;
			
			// aapt resource value: 0x7F060040
			public const int songs_container = 2131099712;
			
			// aapt resource value: 0x7F060041
			public const int tag_accessibility_actions = 2131099713;
			
			// aapt resource value: 0x7F060042
			public const int tag_accessibility_clickable_spans = 2131099714;
			
			// aapt resource value: 0x7F060043
			public const int tag_accessibility_heading = 2131099715;
			
			// aapt resource value: 0x7F060044
			public const int tag_accessibility_pane_title = 2131099716;
			
			// aapt resource value: 0x7F060045
			public const int tag_screen_reader_focusable = 2131099717;
			
			// aapt resource value: 0x7F060046
			public const int tag_transition_group = 2131099718;
			
			// aapt resource value: 0x7F060047
			public const int tag_unhandled_key_event_manager = 2131099719;
			
			// aapt resource value: 0x7F060048
			public const int tag_unhandled_key_listeners = 2131099720;
			
			// aapt resource value: 0x7F060049
			public const int text = 2131099721;
			
			// aapt resource value: 0x7F06004A
			public const int text2 = 2131099722;
			
			// aapt resource value: 0x7F06004B
			public const int time = 2131099723;
			
			// aapt resource value: 0x7F06004C
			public const int title = 2131099724;
			
			// aapt resource value: 0x7F06004D
			public const int two_fragments_layout = 2131099725;
			
			// aapt resource value: 0x7F06004E
			public const int view_tree_lifecycle_owner = 2131099726;
			
			// aapt resource value: 0x7F06004F
			public const int view_tree_saved_state_registry_owner = 2131099727;
			
			// aapt resource value: 0x7F060050
			public const int view_tree_view_model_store_owner = 2131099728;
			
			// aapt resource value: 0x7F060051
			public const int visible_removing_fragment_view_tag = 2131099729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public const int status_bar_notification_info_maxnum = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public const int albuns_layout = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int custom_dialog = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int Main = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int notification_action = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int notification_action_tombstone = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int notification_template_custom_big = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int notification_template_icon_group = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int notification_template_part_chronometer = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int notification_template_part_time = 2131230728;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int app_name = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int btn_call = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int btn_contacts = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int btn_fragments = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int btn_maps_coordinates = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int btn_maps_routes = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int btn_maps_street = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int btn_open_browser = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int status_bar_notification_info_overflow = 2131296264;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int TextAppearance_Compat_Notification = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int TextAppearance_Compat_Notification_Info = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int TextAppearance_Compat_Notification_Line2 = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int TextAppearance_Compat_Notification_Time = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int TextAppearance_Compat_Notification_Title = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int Widget_Compat_NotificationActionContainer = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int Widget_Compat_NotificationActionText = 2131361798;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F020000 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130837504};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F020002,0x7F020003,0x7F020004,0x7F020005,0x7F020006,0x7F020007 }
			public static int[] FontFamily = new int[] {
					2130837506,
					2130837507,
					2130837508,
					2130837509,
					2130837510,
					2130837511};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F020001,0x7F020008,0x7F020009,0x7F02000A,0x7F02000B }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130837505,
					2130837512,
					2130837513,
					2130837514,
					2130837515};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x1010003,0x10100D0,0x10100D1 }
			public static int[] Fragment = new int[] {
					16842755,
					16842960,
					16842961};
			
			// aapt resource value: { 0x1010003,0x10100D1 }
			public static int[] FragmentContainerView = new int[] {
					16842755,
					16842961};
			
			// aapt resource value: 0
			public const int FragmentContainerView_android_name = 0;
			
			// aapt resource value: 1
			public const int FragmentContainerView_android_tag = 1;
			
			// aapt resource value: 1
			public const int Fragment_android_id = 1;
			
			// aapt resource value: 0
			public const int Fragment_android_name = 0;
			
			// aapt resource value: 2
			public const int Fragment_android_tag = 2;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
